FieldAssist/fa_flutter_ui_kit

lib/fa_flutter_ui_kit.dart
lib/src/constants/images.dart
lib/src/modules/splash/splash_page.dart
lib/src/utils/after_layout_mixin.dart
lib/src/utils/index.dart
lib/src/widgets/common/app_logo.dart
lib/src/widgets/common/index.dart
lib/src/widgets/common/launching_growth.dart
lib/src/widgets/common/responsive_container.dart

Asana Link - https://app.asana.com/0/1200109906013623/1200194673221300
Signed-off-by: Aashish <aashishc901@gmail.com>

[Ui Kit] Structure and Splash Page

---

lib/fa_flutter_ui_kit.dart
lib/src/constants/images.dart
lib/src/modules/splash/splash_page.dart
lib/src/utils/after_layout_mixin.dart
lib/src/utils/index.dart
lib/src/widgets/common/app_logo.dart
lib/src/widgets/common/index.dart
lib/src/widgets/common/launching_growth.dart
lib/src/widgets/common/responsive_container.dart

Asana Link - https://app.asana.com/0/1200109906013623/1200194673221300
Signed-off-by: Aashish <aashishc901@gmail.com>

[Ui Kit] Add Structure and Splash Page (#1)

---

.github/PULL_REQUEST_TEMPLATE.md
lib/src/widgets/common/generic_dialog.dart

Added PR Template to the UI Kit.
Fix the Bug in GenericDialog Widget.

[Update]<PR Template> Added PR Template to the UI Kit.

---

example/pubspec.lock
lib/src/modules/login/widgets/code_text_field.dart
lib/src/modules/login/widgets/phone_text_field.dart
pubspec.lock

Changes in EnterCodeTextField class (after upgrading flutter version).
Links :

[Update]<EnterCodeTextField> Changes in EnterCodeTextField class.

---

example/pubspec.lock
lib/src/core/location_info/models/location_data.freezed.dart
lib/src/core/location_info/models/location_data.g.dart
lib/src/data/models/country/country.freezed.dart
lib/src/data/models/country/country.g.dart
pubspec.lock
pubspec.yaml

Updated some packages to the latest version.
Links :

[Update]<pubspec> Updated some packages to the latest version.

---

example/pubspec.lock
lib/src/core/location_info/location_info.dart
pubspec.lock
pubspec.yaml

Upgrade geolocator to 8.1.1
Links :

[Pubspec] Upgrade geolocator to 8.1.1

---

lib/src/modules/common/search_list/integrated_search_bar.dart
lib/src/modules/common/search_list/integrated_search_textfield.dart

Add the autoFocus param.
Links :

[search-list] Add the autoFocus param.

---

lib/src/modules/common/search_list/integrated_search_bar.dart
lib/src/modules/common/search_list/integrated_search_textfield.dart
lib/src/modules/common/search_list/search_list.dart

Modify the logic and UI.
Links :

[search-list] Modify the logic and UI.

---

lib/src/constants/text_style.dart
lib/src/utils/dialog_utils.dart
lib/src/widgets/month_range_picker/month_calendar.dart
lib/src/widgets/month_range_picker/month_view.dart
lib/src/widgets/month_range_picker/selected_month_indicator.dart

Add selected month background colour functionality
Signed-off-by: Vatsal Ketan Gandhi <gandhivatsal17@gmail.com>
Add selected month background colour functionality
Links :

[MonthPickerColour] Add selected colour functionality

---

lib/src/constants/text_style.dart
lib/src/widgets/month_range_picker/month_view.dart
lib/src/widgets/month_range_picker/selected_month_indicator.dart

Change text decoration
Signed-off-by: Vatsal Ketan Gandhi <gandhivatsal17@gmail.com>
Links :

[Rangepicker] Change text decoration

---

lib/src/widgets/common/svg_asset_icon.dart

Add padding member in class SvgAssetIcon.
Links :

[SvgAssetIcon] Add padding member

---

lib/src/modules/common/generic_data_loading/animated_loader.dart

In mt we need thinner AnimatedLoader.
Links :

[AnimatedLoader] Make height of bar customizable

---

lib/src/modules/common/generic_data_loading/animated_loader.dart

Fix the height of background container that contains the loader
Links :

[AnimatedLoader] Fix height of background container

---

example/pubspec.lock
lib/src/widgets/qr_code_scanner/qr_code_scanner.dart
pubspec.lock
pubspec.yaml

Signed-off-by: Ritesh Khadse <r.khadse@flick2know.com>
Added Qr Code scanner.
Links :

[Qr-Scanner] add qr code scanner widget

---

lib/src/widgets/common/animating_location_pin.dart
lib/src/widgets/common/index.dart

Signed-off-by: Ritesh Khadse <r.khadse@flick2know.com>
add animating_location_pin widget
Links :
[common-widget] add animating_location_pin widget

[common-widget] add animating_location_pin widget

---

README.md
example/pubspec.lock
lib/src/widgets/index.dart
lib/src/widgets/qr_code_scanner/qr_code_scanner.dart
pubspec.lock
pubspec.yaml

[Qr-code-scanner] Add Qr Code scanner

---

example/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
example/macos/Flutter/ephemeral/flutter_export_environment.sh
pubspec.lock
pubspec.yaml

Signed-off-by: Raghav Pawar <r.pawar@flick2know.com>
freezed_annotation dependency removed from pubspec.yaml file and being imported directly from fa_flutter_core.
[Asana Task]: https://app.asana.com/0/1202680184734349/1202680184734349

[Remove Dependency] Remove freezed_annotation

---

lib/src/modules/common/data_stream_builder/stream_error_widget.dart

Modify UI to show name, id, time.
Links :

[StreamErrorWidget] Modify UI to show name, id, time.

---

lib/src/widgets/qr_code_scanner/qr_code_scanner.dart

Signed-off-by: Ritesh Khadse <r.khadse@flick2know.com>
https://app.asana.com/0/958356987304923/1202681642081324/f
Extract upi id from Qr_code_scanner when available
Links :

[Qr-code-scanner] extract upi id when available

---

lib/src/modules/common/data_stream_builder/stream_error_widget.dart

Remove isMtError parameter.
Links :

[StreamErrorWidget] Remove isMtError parameter.

---

lib/fa_flutter_ui_kit.dart
lib/src/widgets/common/multi_select_items/bottom_sheet/multi_select_bottom_sheet.dart
lib/src/widgets/common/multi_select_items/bottom_sheet/multi_select_bottom_sheet_field.dart
lib/src/widgets/common/multi_select_items/chip_display/multi_select_chip_display.dart
lib/src/widgets/common/multi_select_items/chip_field/multi_select_chip_field.dart
lib/src/widgets/common/multi_select_items/dialog/mult_select_dialog.dart
lib/src/widgets/common/multi_select_items/dialog/multi_select_dialog_field.dart
lib/src/widgets/common/multi_select_items/multi_select_flutter.dart
lib/src/widgets/common/multi_select_items/util/horizontal_scrollbar.dart
lib/src/widgets/common/multi_select_items/util/multi_select_actions.dart
lib/src/widgets/common/multi_select_items/util/multi_select_item.dart
lib/src/widgets/common/multi_select_items/util/multi_select_list_type.dart

Add to common widgets.
Links :

[MultiSelectItem] Add to common widgets.

---

lib/src/widgets/common/multi_select_items/chip_display/multi_select_chip_display.dart
lib/src/widgets/common/multi_select_items/chip_field/multi_select_chip_field.dart

Wrap text with expanded.
Links :

[MultiSelectChipField] Wrap text with expanded.

---

lib/src/widgets/common/multi_select_items/bottom_sheet/multi_select_bottom_sheet_field.dart
lib/src/widgets/common/multi_select_items/chip_display/multi_select_chip_display.dart
lib/src/widgets/common/multi_select_items/chip_field/multi_select_chip_field.dart

Wrap text in expanded.
Links :

[MultiSelectChip] Wrap text in expanded.

---

lib/src/widgets/qr_code_scanner/qr_code_scanner.dart

Signed-off-by: Ritesh Khadse <r.khadse@flick2know.com>
refactor qr code scanner behaviour for upi id
Links :

[qr-code-scanner] refactor to show upi

---

lib/src/modules/common/data_stream_builder/stream_error_widget.dart

[StreamErrorWidget] Add version number

---

.run/main.dart.run.xml
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
example/macos/Flutter/GeneratedPluginRegistrant.swift
example/pubspec.lock
lib/src/core/location_info/location_info.dart
lib/src/modules/common/generic_data_loading/shimmer_widgets.dart
lib/src/modules/login/widgets/country_picker.dart
lib/src/utils/after_layout_mixin.dart
lib/src/widgets/calendar/widgets.dart
lib/src/widgets/common/common_progress_dialog.dart
lib/src/widgets/common/company_logo.dart
lib/src/widgets/common/multi_select_items/chip_field/multi_select_chip_field.dart
lib/src/widgets/common/progress_dialog/fa_progress_dialog.dart
lib/src/widgets/common/svg_asset_icon.dart
lib/src/widgets/common/svg_asset_img.dart
pubspec.lock
pubspec.yaml

Signed-off-by: Vatsal Gandhi <gandhivatsal17@gmail.com>
Migrate common packages to fa_flutter_core.
Links :

[Packages] Migrate common packages to fa_flutter_core

---

.gitignore
example/.gitignore
example/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
example/macos/Flutter/ephemeral/flutter_export_environment.sh
lib/src/widgets/common/flavor/flavor.dart

Via this PR we are adding some additional flavors.
Links :

[Flavor] Add additional flavors.

---

lib/src/widgets/common/generic_dialog.dart

Currently dialog box only allows to show 2 text only, and single color for both button. But in this pr I have extended dialog box to display third text as description and option to select color of both button separately
Links :

[GenericDialog] Add description

---

example/ios/Podfile
example/ios/Podfile.lock
example/ios/Runner/Info.plist
lib/src/utils/dialog_utils.dart
lib/src/widgets/calendar/calendar.dart
lib/src/widgets/calendar/widgets.dart

Make row and cell width modifiable
Links :

[Calendar] Make row and cell width modifiable

---

lib/src/widgets/common/multi_select_items/bottom_sheet/multi_select_bottom_sheet.dart
lib/src/widgets/common/multi_select_items/bottom_sheet/multi_select_bottom_sheet_field.dart
lib/src/widgets/common/multi_select_items/util/multi_select_actions.dart
pubspec.lock

Make list single select
Links :

[MultiSelectBottomSheet] Make list single select

---

example/macos/Flutter/GeneratedPluginRegistrant.swift
example/pubspec.lock
lib/src/modules/common/search_list/integrated_search_textfield.dart
lib/src/modules/common/search_list/search_list.dart
pubspec.lock
pubspec.yaml

[IntegratedSearchTextField] adding mic button to the searchlist textfield
Links :

[SearchList] Add mic option to search bar

---

example/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
example/macos/Flutter/ephemeral/flutter_export_environment.sh
lib/src/widgets/qr_code_scanner/qr_code_scanner.dart

[qr-scanner] add ui enhancements

---

lib/src/core/location_info/location_info.dart
lib/src/core/location_info/models/location_data.dart
lib/src/core/location_info/models/location_data.freezed.dart
lib/src/core/location_info/models/location_data.g.dart
lib/src/core/location_info/models/place_mark_data/place_mark_data.dart
lib/src/core/location_info/models/place_mark_data/place_mark_data.freezed.dart
lib/src/core/location_info/models/place_mark_data/place_mark_data.g.dart
lib/src/data/models/country/country.freezed.dart

Via this PR we are adding placemark data to Location data field
Links :
[Asana](https://app.asana.com/0/401576460077807/1205158605703631/f)

[LocationData] Add placemark_data field

---

lib/src/widgets/qr_code_scanner/qr_code_scanner.dart

added validations for qr code scanner based on regex
Links :

[qr-scanner] add regex validations check

---

example/android/build.gradle
example/macos/Flutter/GeneratedPluginRegistrant.swift
example/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
example/macos/Flutter/ephemeral/flutter_export_environment.sh
example/pubspec.lock
example/pubspec.yaml
lib/src/config/theme/theme_dark.dart
lib/src/config/theme/theme_light.dart
lib/src/modules/common/generic_data_loading/animated_loader.dart
lib/src/modules/common/search_list/search_app_bar.dart
lib/src/widgets/common/multi_select_items/chip_display/multi_select_chip_display.dart
lib/src/widgets/common/multi_select_items/chip_field/multi_select_chip_field.dart
lib/src/widgets/common/my_circular_progress.dart
lib/src/widgets/common/search_widget.dart
pubspec.lock
pubspec.yaml

Removed all deprecated properties.
Links :

fix(common): migrated to flutter 3.13

---

.gitignore
example/pubspec.lock
lib/src/widgets/qr_code_scanner/qr_code_scanner.dart

https://app.asana.com/0/1151475021442491/1206545458466268/f
Links :

[qr-code-scanner] add functionality to check for duplicates in scanned values

---

lib/src/widgets/common/multi_select_items/bottom_sheet/multi_select_bottom_sheet_field.dart
lib/src/widgets/common/multi_select_items/chip_display/multi_select_chip_display.dart

in this pr add enable boolean to toggle enable and disable 
Links :

fix(multi-select-bottom-sheet): add boolean to toggle enable and disable

---

lib/src/widgets/common/multi_select_items/bottom_sheet/multi_select_bottom_sheet_field.dart
lib/src/widgets/common/multi_select_items/chip_display/multi_select_chip_display.dart

in this pr add boolean to show
remove icon at end 
Links :

fix(multi-select-bottom-sheet): add boolean to show delete icon at end inside chip

---

example/macos/Flutter/GeneratedPluginRegistrant.swift
example/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
example/macos/Flutter/ephemeral/flutter_export_environment.sh
example/pubspec.lock
pubspec.lock
pubspec.yaml

• Migrated flutter to v3.19.4
Links :

[Migration] migrate to v3.19.4

---

example/lib/main.dart
lib/src/config/theme/theme_light.dart

• set useMaterial3 to false
Links :

fix(common): set useMaterial3 to false

---

lib/src/modules/day_start/widgets/day_start_button.dart
lib/src/widgets/common/bottom_action_button.dart

in this PR add gradient and primary color to bottom buttons
Links :
https://app.asana.com/0/1205420401382582/1206938814912297

feat(app-theme): add gradient and primary color to bottom buttons

---

lib/fa_flutter_ui_kit.dart
lib/src/modules/custom_gauge/custom_gauge_painter.dart
lib/src/modules/custom_gauge/index.dart

- implementation of custom arc gauge
Links :
Demo: 

feat(custom-gauge): implementation of custom arc gauge

---

lib/src/core/location_info/location_info.dart

• Added option to enforce geocoding
Links :

fix(location-info): add option for enforcing geocoding

---

lib/src/modules/common/search_list/search_list.dart
lib/src/widgets/common/exit_dialog.dart

add buttons color parameter in exit dialog
Links :

fix(exit-dialog): add buttons color parameter in exit dialog

---

lib/src/modules/common/file_upload/file_uploader.dart
pubspec.lock
pubspec.yaml

- implemented functions for fetching docs 
Links :

feat(file-upload): implemented file service functions

---

lib/src/modules/custom_gauge/custom_gauge_painter.dart

- use target value if current value exceeds target value
Links :

fix(custom-gauge): use target value if current value exceeds target

---

lib/src/modules/custom_gauge/custom_gauge_painter.dart

- draw achievement value to centre of gauge
Links :

fix(custom-gauge): draw achievement value to centre of gauge

---

lib/src/modules/common/file_upload/file_uploader.dart

fix(file-service): allot required file size

---

lib/src/modules/common/file_upload/file_uploader.dart

fix(file-service): provide image quality 

---

lib/src/config/colors.dart
lib/src/config/index.dart
lib/src/modules/common/file_upload/file_uploader.dart
lib/src/widgets/common/base_scaffold.dart
lib/src/widgets/common/index.dart
lib/src/widgets/common/primary_scaffold.dart

index color added 
Links :
[feat(color): adding shade for base]
-[fix(color): index added]

fix: index color added

---

lib/src/modules/common/generic_data_loading/animated_loader.dart

Links :
https://app.asana.com/0/0/1207861139738953/f

fix(loader): add color parameters for animated loader

---

lib/src/config/fonts.dart
lib/src/widgets/order_booking/summary/order_amount_summary.dart

Confirmation : 
- oleo fonts 
- distributor visiblity
Links :
https://docs.google.com/spreadsheets/d/1rJljX3VleeuD0uuaNLcpXWbD2zYHvZVbcLVbNhlRjbY/edit?gid=636862975#gid=636862975
feat(confirmation): fonts and distributor visiblity

feat(confirmation): fonts and distributor visiblity

---

lib/src/widgets/order_booking/summary/order_amount_summary.dart

1. add custom text parameters in order amount summary widget
Links :

enhancement(order-summary): add custom texts in order amount summary widget

---

lib/src/widgets/order_booking/summary/order_amount_summary.dart

*Van stock check page has a dropdown on the payable amount which is not usable*
Links :
https://app.asana.com/0/1203045279492787/1208233599100322/f

fix(summary): visibility of dropdown without data

---

lib/src/widgets/order_booking/summary/order_amount_summary.dart

* Based on boolean QuantityBreakdown can use for single value of string

feat(order-amount-summary) : single value of string with quantity break down

---

lib/src/widgets/order_booking/summary/order_amount_summary.dart

feat(order-amount-summary): add decimal info string

---

lib/src/utils/currency_utils.dart

[TEMP]feat(currency-util): add 2 decimal number formatter for currencies

---

lib/src/utils/currency_utils.dart
lib/src/widgets/order_booking/summary/order_amount_summary.dart

*Flutter App to be international number system compatible*
Links :
https://app.asana.com/0/1203045279492787/1208396483431298/f

feat(currency-utils): add international number system

---

lib/src/utils/currency_utils.dart
lib/src/widgets/order_booking/summary/order_amount_summary.dart

fix(number-system): fix internaltional number system formatting

---

example/macos/Flutter/GeneratedPluginRegistrant.swift
example/pubspec.lock
lib/src/utils/currency_utils.dart
pubspec.lock
pubspec.yaml

fix(currency-util): fix rounding precision error

---

lib/src/utils/currency_utils.dart

feat(currency-util): make decimal data configurable

---

lib/src/widgets/order_booking/summary/order_amount_summary.dart

*Dual Currency.*
Links :
https://app.asana.com/0/1203045279492787/1208893624140931/f

feat(dual-currency): show second currency on summary screen

---

lib/src/widgets/common/common_progress_dialog.dart
lib/src/widgets/common/progress_dialog/progress_dialog.dart

fix(progress-dialog): handle not active and null check issues

---

lib/src/constants/icons.dart
lib/src/widgets/order_booking/summary/order_amount_summary.dart

Links :
https://app.asana.com/0/1205420401315804/1209029095277368/f

enhancement(summary): change rupee icon in order amount summary

---

lib/src/utils/cam_image_picker_util.dart

**_Task: adding camera image picker source to the utils folder._**

feat(camera): add camera source

---

lib/src/widgets/order_booking/summary/order_amount_summary.dart

feat(order-summary): add optional misc widget

---

lib/src/utils/currency_utils.dart

chore: handle decimal rounding edge cases

---

lib/src/widgets/order_booking/summary/order_amount_summary.dart

*BACKLOG[139980]: Configuring UOM on the application*
Links :
https://dev.azure.com/flick2know/Field_Assist/_sprints/taskboard/pod-mt-international-enterprise/Field_Assist/MT%20International%20Enterprise%20Pod/pod-mt-international-enterprise-sprint4?workitem=139980

feat(uom): configure uom on order-amount-summary

---

lib/src/utils/currency_utils.dart

Links :
https://dev.azure.com/flick2know/Field_Assist/_sprints/taskboard/pod-mt-international-cst-maintenance/Field_Assist/MT%20International%20CST%20maintenance%20Pod/pod-mt-international-cst-maintenance-sprint6?workitem=141123

feat(currency-util): add french number system

---

lib/src/utils/currency_utils.dart

fix(french-number): add missing return

---

example/macos/Flutter/GeneratedPluginRegistrant.swift
example/pubspec.lock
lib/fa_flutter_ui_kit.dart
lib/src/app/untrusted_device_widget.dart
pubspec.lock
pubspec.yaml

widget for restricting user for developer mode , autotime and autoTimeZone.
Links :

feat(safe-device): widget for restricting user

---

lib/src/utils/currency_utils.dart

feat(currency-util): add roundNumber method

---

lib/src/utils/currency_utils.dart
plugins/fa_safe_device/example/lib/main.dart
plugins/fa_safe_device/lib/fa_safe_device.dart
plugins/fa_safe_device/lib/fa_safe_device_method_channel.dart
plugins/fa_safe_device/lib/fa_safe_device_platform_interface.dart

fix(currency-utils): exception number format
Links :

fix(currency-utils): exception number format

---

lib/src/utils/index.dart

updates exports for new currency related files.

chore : update exports in index file

---

lib/src/utils/currency/enums.dart

*fix the suffix only.*
Links :

fix(currency-util): fix the suffix of locales

---

lib/src/utils/currency/helper.dart

*Added _convertToArabicIndicDigits method to transform Western digits and separators into Arabic-Indic equivalents.*
Links :

feat(currency): add support for Arabic-Indic digit formatting

---

lib/src/widgets/common/base_scaffold.dart

fix(base-scaffold): add background color

---

lib/src/core/location_info/location_info.dart

remove null assertion operation  
Links :
https://app.asana.com/1/34125054317482/project/404534051288984/task/1210582458702051?focus=true
https://console.firebase.google.com/u/0/project/fa-flutter-gt/crashlytics/app/android:com.flick2know.fieldassist.gt/issues/8cf17aa4542a62547cd0bf5f58a28f0f?time=last-seven-days&types=crash&sessionEventKey=6863E75C028B00212C41C22F0FD8BD82_2100555795561691468
https://console.firebase.google.com/u/0/project/fa-flutter-gt/crashlytics/app/android:com.flick2know.fieldassist.gt/search?time=1749859200000:1750291199000&types=crash&q=13477234 …

fix(locationInfo): remove null assertion operation 

---

lib/src/widgets/common/common_progress_dialog.dart

* Sometimes progress dialog not dismiss. Issue may occur due to disposed context access with static _dialog variable
Links :
[Asana](https://app.asana.com/1/34125054317482/project/1164637464493147/task/1210668146575307?focus=true)

fix(progress-dialog): progress dialog dismiss issue

---

lib/src/utils/currency/helper.dart
pubspec.lock

*passes the isCompact in constructor  of currencyUtil class to make it configurable and updates the other function also..*
Links :

fix(currencyUtil):updates the isCompact logic

---

lib/src/config/colors.dart
lib/src/config/index.dart
lib/src/config/theme/theme_light.dart

style(theme) : Migrate AppColors in UI_Kit

---

lib/src/widgets/common/data_loading_progress/data_loading_progress_widget.dart

Change apiStatus enum is pascal case
Links :

chore(misc): change enum name ApiStatus 

---

lib/src/widgets/common/index.dart
lib/src/widgets/common/step_progress.dart

feat(step-progress): add step progress bar widget for visual step tracking

---

lib/src/config/theme/theme_light.dart
plugins/fa_safe_device/example/lib/main.dart
plugins/fa_safe_device/lib/fa_safe_device_method_channel.dart

*Removed redundant systemOverlayStyle configuration from light theme AppBar for cleaner theme handling.*
https://app.asana.com/1/34125054317482/task/1211101141131805?focus=true

fix(appbar-theme):updates the status bar theme
